---
version: "3"

services:
  pihole:
    container_name: littlelink
    image: ghcr.io/kdpuvvadi/littlelink-docker:latest
    ports:
      - "8080:80"
    volumes:
      - '~/littlelink/html:/usr/share/nginx/html/'
      - '~/littlelink/config:/etc/nginx/conf.d/'
    restart: unless-stopped